import websockets  # Pour la gestion du websocket
import asyncio  # Pour les fonctions asynchrone
import qrcode  # Pour manipuler les QRCode
import json  # Pour les traitements JSON
import threading  # Pour la gestion des threads
import cmd  # Pour la création d'un CLI
import os  # Pour intéragir avec le système
import subprocess  # Pour le lancement d'une commande system
import getpass  # Pour récupérer le nome d'utilisateur
from collections import deque

try:
    from colorama import Fore, Back, Style, init
    # init(autoreset=False) configure colorama pour qu'il intercepte les flux systèmes
    init()
    
    # Définition des styles et couleurs du terminal
    BLUE  = Fore.BLUE + Style.BRIGHT
    RED   = Fore.RED + Style.BRIGHT
    GREEN = Fore.GREEN + Style.BRIGHT
    CYAN  = Fore.CYAN + Style.BRIGHT
    RESET = Style.RESET_ALL
except ImportError:
    # Si colorama n'est pas installé, on crée des variables vides pour éviter que le code ne plante
    print("[!] Warning: 'colorama' package is missing. Installing it with 'pip install colorama' is recommended for colors.")
    BLUE = RED = GREEN = CYAN = RESET = ""


class WTerminal(cmd.Cmd):
    intro = f"""{RED}

██╗    ██╗████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗
██║    ██║╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║
██║ █╗ ██║   ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║
██║███╗██║   ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║
╚███╔███╔╝   ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗
 ╚══╝╚══╝    ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝


              {RESET}{BLUE}[ WhatsApp Client for CLI ]  -  {RESET}{GREEN}v1.0.0 (Alpha){RESET}


   +--------------------------------------------------------------------+
   |                                                                    |
   |           {BLUE}---> Type /help to see available commands <---{RESET}           |
   |                                                                    |
   +--------------------------------------------------------------------+

    """
    USER = getpass.getuser()
    prompt = f"{BLUE}┌──({RESET}{GREEN}{USER}{RESET}{BLUE}㉿wterminal)-[{RESET}{RED}~{RESET}{BLUE}]\n└─${RESET} "

    def __init__(self):
        super().__init__()
        self.current_dir = os.path.dirname(os.path.abspath(__file__))
        self.contact_file = os.path.join(self.current_dir, "contacts.json")
        self.message_folder_path = os.path.join(self.current_dir, "Messages")
        self.new_msg_list_file_path = os.path.join(self.current_dir, "Messages", "newMessageList.txt")
        self.ws = None
        self.loop = asyncio.new_event_loop()
        self.net_threading = None
        self.qr_locked = False
        self.contacts = self.load_contacts()
        self.create_m_folder()

    # Create message folder
    def create_m_folder(self):
        os.makedirs(self.message_folder_path, exist_ok=True)

    """ IMPLEMENT CONTACT SYSTEM """

    # Load contact
    def load_contacts(self):
        if os.path.exists(self.contact_file):
            try:
                with open(self.contact_file, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as e:
                print(f"\n[!] Can't read contact : {e}")
        return {}

    # Save contact
    def save_contact(self):
        try:
            with open(self.contact_file, "w", encoding="utf-8") as f:
                # Write change in the file, f or contact_file
                json.dump(self.contacts, f, indent=4, ensure_ascii=False)
        except Exception as e:
            print(f"\n[!] Error occured when trying to save : {e}")

    # Get name from id
    def get_name_from_id(self, sender_id):
        for aliase, jID in self.contacts.items():
            if jID == sender_id:
                return f"{aliase.upper()}"
        return sender_id

    """ CONNECT TO THE BACKEND """

    # Start network loop using asyncio
    def start_net_loop(self):
        asyncio.set_event_loop(self.loop)
        self.loop.run_until_complete(self.main_network_loop())

    # Connect to the backend using websocket
    async def main_network_loop(self):
        # URL to be used for connecting the app to the backend
        uri = "ws://localhost:8088"

        while True:
            try:
                # Connecting to the websocket generated by the backend.
                print("[+] Trying to connect the app to the backend.")
                self.ws = await websockets.connect(uri)
                print("\n[-] The app is now connected to the backend\n")
                self.qr_locked = False

                async for socket in self.ws:
                    await self.handle_incoming_message(socket)

            # If there a error during the connection session
            except Exception as e:
                print(f"[!] Connection error : {e}")

            # Try to reconnect
            print("[!] Trying to reconnect to the backend in 2 seconds..")
            if self.ws:
                await self.ws.close()
            self.ws = None
            await asyncio.sleep(2)

    
    # Handle incoming message using socket
    async def handle_incoming_message(self, socket):
        try:
            data = json.loads(socket)

            # If the message type is QR then ask user to scan QRCode
            if data.get("type") == "QR":
                if not self.qr_locked:
                    # Lock the QRCode
                    self.qr_locked = True
                    print("[+] Please scan QR code\n")

                    # Draw QRCode using qrcode module
                    qr = qrcode.QRCode(border=1)
                    qr.add_data(data["data"])
                    qr.make(fit=True)
                    qr.print_ascii(invert=False)

            # If we got status as a type
            elif data.get("type") == "STATUS":
                print(f"[+] Status : {data['data']}")

            # If we got new message as event.
            elif data.get("event") == "NEW_MESSAGE":
                user_name = data.get("sender_name", "Unknown")
                user_id = data.get("sender_id", "Unknown")
                text = data.get("text")
                date = data.get("date")

                print(f"New message\n>>> [{date}] : {user_name.upper()} : {user_id}\n>>> {text}")
                print(self.prompt, end="", flush=True)
        
        except Exception as e:
            print(f"[!] Error processing message : {e}")

    """ TERMINAL IMPLEMENTATION FOR FRONT END """

    # List of message or contact
    def do_Show(self, arg):

        # Create a list of argument by using split() method
        commandSpliter = arg.split(" ", 1)
        command = commandSpliter[0]

        # Check if syntax is correct or not
        if len(commandSpliter) < 1:
            print("\n[!] Syntax error : Try 'Show <argument>' (e.g., Show New-message).")

        # When user type new-message as an argument
        if command == "new-message":
            try:
                with open(self.new_msg_list_file_path, "r", encoding="utf-8") as f:
                    list_of_new_msg = f.read()
                    print(f"List of new message\n {list_of_new_msg}")
            except Exception as e:
                print(f"[!] Error : {e}")
        
        # When user type contacts as an argument
        elif command == "contacts":
            try:
                print("List of contacts :\n")
                for contact_key, contact_value in self.contacts.items():
                    print(f" -> {contact_key} - {contact_value}")
            except Exception as e:
                print(f"[!] Error : {e}")

        # When user type chats as an argument
        elif command == "chats":
            try:
                print("List of chats :")
                for contact_key in self.contacts.keys():
                    print(f" -> {contact_key}")
            except Exception as e:
                print(f"[!] Error : {e}")

        # When user type anything as an argument        
        else:
            print("[!] Invalid argument : use 'chats' or 'contacts' or 'new-message'..")
            return

    # Add contact
    def do_Add(self, arg):

        # Creat a list of argument by using split() method
        commandSpliter = arg.split(" ", 1)
        user_name, user_jid = commandSpliter[0], commandSpliter[1]
        newUser_message_file_path = os.path.join(self.message_folder_path, f"{user_name}.txt")

        # Check if the syntax is correct or not.
        if len(commandSpliter) < 2:
            print("\n[!] Syntax error : Try 'Add <contact_name> <remodeJID>' (e.g., Add Aina xxxxx@s.whatsapp.com).")
            return
        
        # Add key-value and save using save_contact() methode
        self.contacts[user_name] = user_jid
        self.save_contact()

        # Create the message file for the new user added
        with open(newUser_message_file_path, "w", encoding="utf-8") as f:
            pass

    # Connect to the backend
    def do_Connect(self, arg):
        try:
            if self.net_threading and self.net_threading.is_alive():
                print("[!] Already connecting or connected.")
                return
            self.net_threading = threading.Thread(
                target=self.start_net_loop, daemon=True
            )
            self.net_threading.start()
        except Exception as e:
            print(f"\n[!] Connection error : {e}\n")

    # Read message
    def do_Read(self, arg):

        # Check if user typed arg after Read command
        if not arg:
            print("\n[!] Syntax error : Try 'Read <contact_name>' (e.g., Read Aina).\n")
            return

        # Lower username
        user_name = arg.strip().lower()

        # Check if contact_name exists on the contact file.
        contact_found = None
        for name in self.contacts.keys():
            if name.lower() == user_name:
                contact_found = name
                break

        # Show error if not contact_found
        if not contact_found:
            print(f"[!] Contact error : {arg} doesn't appear in your list of contact.")
            return

        # Prepare the path of the file we want do read and check if path exists
        msg_to_read_path = os.path.join(self.message_folder_path, f"{user_name}.txt")
        if not os.path.exists(msg_to_read_path):
            print(f"[!] Path error : {msg_to_read_path} do not exist.")
            return

        # Read last 2 messages
        try:
            with open(msg_to_read_path, "r", encoding="utf-8") as f:

                # Get usefull lines
                usefull_lines = (lines for lines in f if lines.strip())

                # Read only the two last messages using deque method
                two_last_msg = deque(usefull_lines, maxlen=2)

                # Print 2 last message
                print(f"[ Last 2 message with {contact_found.upper()} ]")
                if not two_last_msg:
                    print(f">>> No message with {contact_found.upper()}")
                    return
                else:
                    for lines in two_last_msg:
                        parts = lines.strip().split("-", maxsplit=2)

                        # Check the length of lines
                        if len(parts) == 3:
                            date = parts[0].strip()
                            username = parts[1].strip()
                            text = parts[2].strip()

                            print(f"{date} | {username.upper()} :")
                            print(f" └─> {text}\n")
                        else:
                            print(f"{lines.strip()}")

        except Exception as e:
            print(f"[!] Message processing error : {e}")

    # Send message [send 1 salut]
    def do_Send(self, arg):
        parts = arg.split(" ", 1)

        if len(parts) < 2:
            print("\n[!] Syntax error : Try 'Send <contact_name> <message>' (e.g., Send Aina Salut!).\n")
            return

        target, message = parts[0], parts[1]

        if self.ws:
            messageObject = {
                "action": "SEND_MESSAGE",
                "to": target,
                "text": message,
            }

            asyncio.run_coroutine_threadsafe(
                self.ws.send(json.dumps(messageObject)), self.loop
            )
            print(f"[+] Message sent to {target}")

        else:
            print("\n[!] Error occured : Message not sent \n")

    # Exit WTerminal
    def do_Exit(self, arg):
        print("\n[-] Closing WTerminal ...\n")

        if self.ws:
            asyncio.run_coroutine_threadsafe(self.ws.close(), self.loop)

        # Stop cmd loop
        return True

    # Clear console
    def do_Clear(self, arg):
        # Clear console using ANSI command
        subprocess.run(
            'cls' if os.name == 'nt' else 'clear', shell=True
        )

    # Create an aliase for do_command
    do_Quit = do_Exit
    do_quit = do_Exit
    do_exit = do_Exit
    do_read = do_Read
    do_add = do_Add
    do_show = do_Show
    do_connect = do_Connect
    do_send = do_Send
    do_cls = do_Clear
    do_clear = do_Clear


if __name__ == "__main__":
    try:
        WTerminal().cmdloop()
    except KeyboardInterrupt:
        print("\n[-] WTerminal is closed\n")
